### ISSUE TITLE
`mix edib --ssh-keys` fails to pull private repo when ssh key not named id_rsa

### ISSUE THREAD

**Issue by seanohalpin** [edib-tool/mix-edib#11]
It appears that edib fails to pull private repos if your ssh private key is not called `id_rsa` (i.e. the default filename for the protocol).

I'm using something like this in my `~/.ssh/config` to get around the issue:

```
Host git.example.com
  Hostname       git.example.com
  IdentityFile   ~/.ssh/id_with_non_default_name
  IdentitiesOnly yes
```

I got the solution from http://stackoverflow.com/questions/4565700/specify-private-ssh-key-to-use-when-executing-shell-command-with-or-without-ruby/11251797#11251797

Also, although it's obvious in retrospect, it might be helpful to point out in the docs for `--ssh-keys` that the key needs to be passwordless.

**Comment by seanohalpin** [comment]
Apologies - I note that you do point out the need for passwordless keys in the comment for `host_ssh_dir` in `lib/edib/defaults.ex`.

P.S. Thanks for this great tool!

**Comment by asaaki** [comment]
Nevertheless I will add it to the public documentation as well.
It should be clear for a user without digging into the source code.
Thanks for the pointer, will fix this soon.

**Comment by asaaki** [comment]
No active development.
