### ISSUE TITLE
Build for different environments

### ISSUE THREAD

**Issue by migore** [edib-tool/mix-edib#13]
I have two different environments that I want to build images, staging and prod. I tried to do `MIX_ENV=staging mix edib` but it built with the production configurations.

Is there a way to do it?

**Comment by asaaki** [comment]
Currently EDIB does not respect a MIX_ENV variable set outside of the docker container run.
I didn't need that previously because all builds were intended to be prod-only.
We can change that behaviour, of course. (I don't see a reason why it should not be configurable.)

**Comment by migore** [comment]
This issue is fixed by PR #14
