### ISSUE TITLE
Use Distillery

### ISSUE THREAD

**Issue by deini** [edib-tool/mix-edib#15]
Now that Distillery is in beta, could we use this instead of exrm?

**Comment by asaaki** [comment]
Great suggestion, I'll check this within the next days.

**Comment by rowpsmo1859** [comment]
As noted above I tried to experiment with the process. The configs are a bit different for distillery ( they must be present in a ~/rel/ folder). I also had to alter a couple of other steps in the process (images and scripts. I had to modify the docker-edib-tool image).

The experiment is still on its way. 

I'll try to throw a couple of hours on this but not sure I'll be able to anytime soon :(

**Comment by asaaki** [comment]
@JeremyBellows Thanks for your efforts.

For all and everybody interested in this change:
Sorry, I was (and still am) pretty busy these days.
Next week I'm at the EUC2016 conf and afterwards I hope to have more focus and energy for the required changes in the EDIB toolchain.

**Comment by rowpsmo1859** [comment]
I think I got it working. Unfortunately my build process is broken due to the tar limitation on file name length. Been trying to figure out where it is coming from (probably a dependency). 

I'll work on pushing the prototype up. It just needs to be tested

**Comment by rowpsmo1859** [comment]
Here's what I have so far

Docker edib tool - https://github.com/JeremyBellows/docker-edib-tool/tree/15-UpgradeToDistillery
mix-Edib - https://github.com/JeremyBellows/mix-edib/tree/15-UseDistillery

I ran into an issue with erts versions and opened #18

**Comment by jcelliott** [comment]
Rebuilding the Docker image chain using those two forks worked for me with two additional changes:
- Changed the version of Erlang to 19: https://github.com/edib-tool/docker-base-erlang
- The check-distillery script on @JeremyBellows' fork didn't work for me even though I had distillery installed, so I just commented it out and everything seemed to work fine (https://github.com/JeremyBellows/docker-edib-tool/blob/15-UpgradeToDistillery/edib/check-distillery.mk)

**Comment by asaaki** [comment]
The base erlang image is also officially updated to 19.x now btw.

**Comment by asaaki** [comment]
@JeremyBellows Can you rebase and rebuild your changes against the updated toolchain to see if it (still/finally) works? (docker image edib-tool version: `0.8.3`, mix-edib: `1.3.3`)

**Comment by rowpsmo1859** [comment]
It works! Tested successfully on my project.

I'll submit the pull requests shortly

The check-distillery.mk script is an exact copy of check-exrm.mk with the word exrm replaced with distillery. It works for me. Make sure to expose distillery as a dependency in the release.

**Comment by rowpsmo1859** [comment]
Two live pull requests
https://github.com/edib-tool/mix-edib/pull/20
and
https://github.com/edib-tool/docker-edib-tool/pull/7

Let me know if there is anything else I need to do :)

**Comment by asaaki** [comment]
Done. 🎉
