### ISSUE TITLE
Process should remove ssh keys 

### ISSUE THREAD

**Issue by kjord1** [edib-tool/mix-edib#16]
After installing dependencies the process should remove the ssh keys imported.  Leaving them in the docker image makes them easily accessible by others.

**Comment by asaaki** [comment]
Can you elaborate on, when and where which others could access the keys?
A reproducible step-by-step walkthrough would be nice, so I can understand, where you see the threat.

**Comment by rowpsmo1859** [comment]
@kjord1 Correct me if I'm wrong,

The concern is that leaving ssh keys used for gathering dependencies is unnecessary after the build step and a potential security risk since the ssh keys are saved inside of the docker image.

Anyone who manages to grab the docker image, has access to the ssh keys.

**Comment by asaaki** [comment]
No response. Closed.
(Open a new issue with more in-depth details if something needs to be fixed.)
