### ISSUE TITLE
Tar issue when using distillery and building using edib

### ISSUE THREAD

**Issue by rowpsmo1859** [edib-tool/mix-edib#18]
I have the distillery packages working but I am running into a packaging issue that I think is caused by the version of ERTS installed.

The docker edib image uses 7.3.1

I can build the release successfully when using 8.0.2 locally

How can we go about updating the version of ERTS on the docker build image?

**Comment by rowpsmo1859** [comment]
This is the stack trace that is printed

```
{{case_clause,
|      {'EXIT',
|          {function_clause,
|              [{filename,join,[[]],[{file,"filename.erl"},{line,393}]},
|               {erl_tar,split_filename,4,[{file,"erl_tar.erl"},{line,471}]},
|               {erl_tar,create_header,3,[{file,"erl_tar.erl"},{line,400}]},
|               {erl_tar,add1,4,[{file,"erl_tar.erl"},{line,323}]},
|               {erl_tar,foreach_while_ok,2,[{file,"erl_tar.erl"},{line,1000}]},
|               {systools_make,add_to_tar,3,
|                   [{file,"systools_make.erl"},{line,1879}]},
|               {systools_make,add_appl,7,
|                   [{file,"systools_make.erl"},{line,1750}]},
|               {systools_make,'-add_applications/5-fun-0-',6,
|                   [{file,"systools_make.erl"},{line,1569}]}]}}},
|  [{systools_make,'-add_applications/5-fun-0-',6,
|       [{file,"systools_make.erl"},{line,1569}]},
|   {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
|   {systools_make,add_applications,5,[{file,"systools_make.erl"},{line,1568}]},
|   {systools_make,mk_tar,6,[{file,"systools_make.erl"},{line,1562}]},
|   {systools_make,mk_tar,5,[{file,"systools_make.erl"},{line,1538}]},
|   {systools_make,make_tar,2,[{file,"systools_make.erl"},{line,336}]},
|   {'Elixir.Mix.Releases.Archiver',make_tar,1,
|       [{file,"lib/mix/lib/releases/archiver.ex"},{line,45}]},
|   {'Elixir.Mix.Releases.Archiver',archive,1,
|       [{file,"lib/mix/lib/releases/archiver.ex"},{line,17}]}]}
| ==> Problem generating release tarball:
|     {:tar_generation_error, :unknown}

```

which is a related to https://github.com/bitwalker/distillery/issues/39

My hypothesis is that upgrading the erts version on the docker build image will resolve this issue since the tar generation works locally using version 8.0.2.

**Comment by rowpsmo1859** [comment]
This is the change log for 8.0.2
http://erlang.org/pipermail/erlang-questions/2016-July/089745.html

> ---
> 
>   --- erts-8.0.2 ------------------------------------------------------
> 
> ---
> 
>   The erts-8.0.2 application can be applied independently of other
>   applications on a full OTP 19 installation.
> 
>   --- Fixed Bugs and Malfunctions ---
> 
>    OTP-13731    Application(s): erts
>                 Related Id(s): ERL-188
> 
> ```
>             Fix scheduler deadlock bug in ets:update_counter/4 when
>             key is not found and inserting the default object
>             causes the table to grow.
> ```
> 
>    OTP-13732    Application(s): erts
>                 Related Id(s): seq13142
> 
> ```
>             Fix VM abort "Overrun stack and heap" in garbage
>             collection triggered by a bsl operation and some very
>             specific heap conditions.
> ```
> 
>   Full runtime dependencies of erts-8.0.2: kernel-5.0, sasl-3.0,
>   stdlib-3.0

**Comment by rowpsmo1859** [comment]
Which is in version
Erlang OTP 19.0.2

And is not available on the Alpine Linux Package Manager yet

https://pkgs.alpinelinux.org/packages?name=erlang-erts&branch=&repo=&arch=&maintainer=

**Comment by rowpsmo1859** [comment]
I contacted the maintainer asking if he could update the version to 19.0.2

**Comment by rowpsmo1859** [comment]
The version has been updated. The docker image chain starting from docker-base-erlang needs to be upgraded to version 19.0.2

**Comment by asaaki** [comment]
Will update the chain soon. Thanks for your efforts! 🙇

**Comment by asaaki** [comment]
@JeremyBellows I've updated the tool chain. Please retry and use mix-edib `1.3.3`.

**Comment by rowpsmo1859** [comment]
This is a bug with ERTS and with long file names. One of my projects is broken due to this and I'm still narrowing down the possibilities. I'm going to close this for now because there is nothing else to be done on edib

**Comment by asaaki** [comment]
Oh, sorry to hear that.
Good luck with finding a solution!

If you have an issue or PR open on Erlang/OTP for it, feel free to link it here (just out of curiosity).

**Comment by rowpsmo1859** [comment]
Will do! Thanks for your help! :D

**Comment by rowpsmo1859** [comment]
I ran a series of manual tests on the architecture of my project and found that it was indeed a long file name (specifically an image).

The weird part is that renaming the file, clearing docker from the system, and adding cache flags to docker did not fix the edib build process. 

I built a new project from scratch (copying over the files one at a time) and confirmed that it was the images that caused it to fail. After failing once however, the edib task would fail regardless of any changes made! 

The solution was to delete the directory locally, clone the project, and then removing files with long names (filename + path must not be greater than 100 chars) and building. This caused the edib task to work.

Any ideas on why this works?

**Comment by asaaki** [comment]
Which OS and Docker do you use?

**Comment by rowpsmo1859** [comment]
Linux Mint 

Linux version 4.4.0-31-generic (buildd@lgw01-16) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016

Docker version 1.11.2, build b9f10c9

**Comment by asaaki** [comment]
Hm, okay.
I only had similar issues on OSX, when it was based on a Virtualbox VM and the file syncing was not working properly.
I wouldn't expect such things to happen on Linux.

**Comment by rowpsmo1859** [comment]
I'm closing this until anything further presents itself
