### ISSUE TITLE
Server not running?

### ISSUE THREAD

**Issue by deini** [edib-tool/mix-edib#19]
I've use `mix-edib` for 3 projects, I'm trying to setup a 4th one but I can't get it to work and I'm not sure what I'm missing.

```
❯ docker run --rm -e "PORT=4000" -p 4000:4000 deini/ammo_api:0.0.1
created directory: '/app/running-config'
Exec: /app/erts-7.3.1/bin/erlexec -noshell -noinput +Bd -boot /app/releases/0.0.1/ammo_api -mode embedded -config /app/running-config/sys.config -boot_var ERTS_LIB_DIR /app/erts-7.3.1/../lib -env ERL_LIBS /app/lib -pa /app/lib/ammo_api-0.0.1/consolidated -args_file /app/running-config/vm.args -- foreground
Root: /app
```

This is a super simple phoenix `--no-brunch --no-ecto` project, I feel I'm missing something super basic, any ideas?

**Comment by deini** [comment]
Disregard, I did a dumb. Literally forgot to set `server: true` in my prod config.

**Comment by asaaki** [comment]
Don't worry. That exact thing happened quite often to me, too. 😅
