### ISSUE TITLE
Include vm.args in release

### ISSUE THREAD

**Issue by tmjoen** [edib-tool/mix-edib#2]
Hi and thanks for a great tool!

I'm trying to get my vm.args included in the release build. According to exrm, it should be as easy as adding my custom `vm.args` to `rel/vm.args`, but it seems that the `rel` directory is ignored when rsyncing the source to the build directory. Is there anyway around this?

Thanks again!

**Comment by asaaki** [comment]
edib skips the `rel` directory to avoid any issue with previous builds in- or outside of the docker environment. I'll check how easy it is to include the `rel/vm.args` when rsyncing. Any other files which might be of interest in this particular directory?

**Comment by asaaki** [comment]
Since it is an edib-tool issue: https://github.com/edib-tool/docker-edib-tool/issues/3

**Comment by edgurgel** [comment]
I think you can safely rsync excluding just `rel/project_name`

**Comment by asaaki** [comment]
I'll give it a try.
