### ISSUE TITLE
[distillery] rel/config.exs determination

### ISSUE THREAD

**Issue by asaaki** [edib-tool/mix-edib#21]
For distillery to work properly a `rel/config.exs` is needed in the project.

This issue is here to discuss different options to deal with it.

Current solutions could be:
- Just document the fact and do nothing; build will fail later in the process if file is missing
- Document the fact, but also let `mix edib` warn/fail before starting any work
- Auto-generate the file in the build process if missing (`mix release.init`), the defaults could be sufficient for most use-cases (like it was with `exrm` as well)
- Combination of the previous 2 options (warn before build + autogenerate)

Any further ideas?

**Comment by dplummer** [comment]
I'm running into this with distillery and an umbrella app. Getting:

```
| cd /build/app && mix release --env=prod
| ==> You are missing a release config file. Run the release.init task first
```

But I have a `rel/config.exs` file.

**Comment by dplummer** [comment]
As a hack to get around this, I added an alias to my `mix.exs`:

``` elixir
  defp aliases do
    [release: ["release.init", "release"]]
  end
```

**Comment by vic** [comment]
I vote for `Document the fact, but also let mix edib warn/fail before starting any work` as it's anyways required by distillery (and `mix release.init` is [documented](https://hexdocs.pm/distillery/getting-started.html#installation-setup) as first step) also I dont think edib should generate it automatically.

**Comment by asaaki** [comment]
No active development.
