### ISSUE TITLE
Missing distillery release file.

### ISSUE THREAD

**Issue by derailed** [edib-tool/mix-edib#22]
Trying out edib on my umbrella project using distillery and running into the following issue:

> mix edib

....
| ==> You are missing a release config file. Run the release.init task first
...

I did generate the distillery release config file using mix release.init but the file resides in rel which is excluded from the initial rsync. 

Is there a work around or am I missing something else?

Thanks!!

**Comment by asaaki** [comment]
Hm, I have to check. In a local test and for https://github.com/edib-tool/edib-app-test-ci, but both are not umbrella projects.
I haven't done any umbrella support yet, but will definitely look into it.

**Comment by derailed** [comment]
Thanks Christoph!! Kind of stuck right now. edib think I have no distillery
config given the only place it gets copied is in rel/config.exs which does
not get rsynced during the build. Don't think the umbrella is the issue
here but could be if everyone can successfully build img in regular apps...

**Comment by deini** [comment]
Non-umbrella app, getting the same error. 💃

**Comment by asaaki** [comment]
No active development.
