### ISSUE TITLE
How do you develop this tool?

### ISSUE THREAD

**Issue by dplummer** [edib-tool/mix-edib#26]
I'm trying to add caching of the `_build` and `deps` directories to speed up our build time in our CD environment. I see there's an option for `--edib`, but it doesn't appear to be used?

1. Is it possible to change which edib docker image is used?
2. Generally, how do you do development work on this project? Specifically, if I wanted to make a change to any of the projects (docker-edib-tool, mix-edib, etc), how would I used the changed version locally?

**Comment by DianaOlympos** [comment]
Fixed, you can now use the `--edib` flag.
