### ISSUE TITLE
Exposing Port

### ISSUE THREAD

**Issue by nmohoric** [edib-tool/mix-edib#32]
Any way already in here to expose a port? 

It seems easy enough to do (I believe it will just need to add in front of the CMD, I see a fixture doing it so it seems possible but from what I can TELL it isn't in here.

If not, any objections to me adding it?

**Comment by asaaki** [comment]
Sounds reasonable.
Looking forward to a PR! ✨

**Comment by asaaki** [comment]
No active development.
