### ISSUE TITLE
Release actual code on hex

### ISSUE THREAD

**Issue by carlo-colombo** [edib-tool/mix-edib#5]
Hi, 
The last version available on hex is the 0.5.1 that use elixir 1.1.x, would you mind to publish a new version on hex that would use elixir 1.2.x avoiding to have to add the dependency as a git repository.

Thanks

**Comment by asaaki** [comment]
I've released version `0.6.1` some minutes ago. Happy building! 💖

**Comment by carlo-colombo** [comment]
Thanks

Il sab 7 mag 2016, 12:07 Christoph Grabo notifications@github.com ha
scritto:
