### ISSUE TITLE
Building projects with umbrella subprojects

### ISSUE THREAD

**Issue by fredriksvensson** [edib-tool/mix-edib#6]
EDIB can't handle umbrella subprojects, since the source is mounted on /source . When mix looks for ../sub_project it will fail.

To enable it one way is to make EDIB.Defaults.current_dir (renamed to source_dir?) and container_source_dir configurable.

**Comment by fredriksvensson** [comment]
Just saw that you had this on you other repo.

**Comment by asaaki** [comment]
I just carried over the issue to this repo, see #7

**Comment by asaaki** [comment]
I also haven't really looked into that yet. If this is a really desired feature I'll investigate.

**Comment by ijcd** [comment]
Distillery would help here. https://github.com/edib-tool/mix-edib/issues/15

**Comment by asaaki** [comment]
@ijcd Thanks for the note. 🙇

**Comment by asaaki** [comment]
No active development.
